### PR TITLE
Py3k compatible

### PR DESCRIPTION
**Pull request by tyb0807**
@rhelmot

### CODE REVIEW

**Comment by rhelmot** [comment]
The builtins and future modules don't come with python; they have to be marked as dependencies.

**Comment by rhelmot** [comment]
also, like, this super doesn't work at all, did you even try running it

**Comment by tyb0807** [comment]
I just removed all the `builtins` imports and it runs for both python 2 and 3 now. I think the `builtins` package is not super useful at all. Don't know why the guy of `future` recommends people to use it though.  However the future package is required for Python2/3 compatibility. I've marked it as dependency. The `past` package is also in `future`.

**Comment by rhelmot** [comment]
Thanks!

**Pull request merged**
